blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions
    url: https://github.com/weareseeed/react-square-web-payments-sdk/discussions
    about: Please ask and answer questions here.
  - name: 📄 Web Payments SDK Overview
    url: https://developer.squareup.com/docs/web-payments/overview
    about: Learn more about the Web Payments SDK with examples and tutorials.
  - name: 📄 Web Paymnents SDK Reference
    url: https://developer.squareup.com/reference/sdks/web/payments
    about: Learn with the API Reference for the Web Payments SDK.
