name: Build, lint, test and build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }} 📦
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Lint 🔥
        run: yarn lint

      - name: Test 🧪
        run: yarn test

      - name: Build on Node ${{ matrix.node }} and ${{ matrix.os }} 🏗
        run: yarn build
